# -*- coding: utf-8 -*-
"""quant dolares y soja

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14fuDUhwCEiKsHmGorjh1ECp_f03lCAp2
"""

!pip install statsmodels patsy

"""
SISTEMA DE TRADING DE REVERSIÓN - FUTUROS DE SOJA
Script corregido: carga dos Excel (NOV y DIC), ajusta regresión, test de cointegraci\u00f3n,
ADF sobre spread y residuos, calcula z-scores (estático y rolling), genera gráficos
y exporta resultados a Excel.

Uso: editar CONFIG con las rutas de los archivos Excel y ejecutar.
Requiere: pandas, numpy, matplotlib, scipy, statsmodels
"""

import warnings
warnings.filterwarnings("ignore")

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

# imports que pueden tardar o fallar: los hacemos al principio para fallar temprano
try:
    import statsmodels.api as sm
    from statsmodels.tsa.stattools import adfuller, coint
except Exception as e:
    raise ImportError(
        "Este script requiere statsmodels. Instalalo con: pip install statsmodels\nDetalle: " + str(e)
    )

# --------------------------------------------------
CONFIG = {
    "excel_dic": "DICIEMBRE2.xlsx",   # archivo con precios de DIC
    "excel_nov": "NOVIEMBRE1.xlsx",  # archivo con precios de NOV
    "fecha_col": 0,                    # indice de la columna con fecha en Excel (0-based)
    "precio_col": 11,                  # indice de la columna con precio en Excel (0-based)
    "zscore_umbral": 1.5,              # umbral para señales
    "coint_pvalue_max": 0.05,          # p-value max para considerar cointegración
    "rolling_window": 60,              # ventana rolling para z-score adaptativo (en observaciones)
    "output_excel": "resultado_reversion.xlsx", # archivo donde exportar tablas
}

# --------------------------------------------------
# ======= CARGA Y EMPALME DE SERIES ================
# --------------------------------------------------
def cargar_series(cfg=CONFIG):
    """Carga los Excel y entrega un DataFrame con Fecha, NOV, DIC y Spread.
    Se asume que cada Excel no tiene header y las columnas se eligen por indices.
    """
    if not os.path.exists(cfg["excel_nov"]):
        raise FileNotFoundError(f"Archivo NOV no encontrado: {cfg['excel_nov']}")
    if not os.path.exists(cfg["excel_dic"]):
        raise FileNotFoundError(f"Archivo DIC no encontrado: {cfg['excel_dic']}")

    nov = pd.read_excel(cfg["excel_nov"], header=None)
    dic = pd.read_excel(cfg["excel_dic"], header=None)

    # Normalizar columnas Fecha y Precio
    nov_cols = nov.copy()
    dic_cols = dic.copy()

    nov_cols["Fecha"] = pd.to_datetime(nov_cols.iloc[:, cfg["fecha_col"]], errors="coerce")
    dic_cols["Fecha"] = pd.to_datetime(dic_cols.iloc[:, cfg["fecha_col"]], errors="coerce")

    nov_cols["Precio"] = pd.to_numeric(nov_cols.iloc[:, cfg["precio_col"]], errors="coerce")
    dic_cols["Precio"] = pd.to_numeric(dic_cols.iloc[:, cfg["precio_col"]], errors="coerce")

    # Filtrar fechas en común
    fechas_comunes = sorted(set(nov_cols["Fecha"]).intersection(set(dic_cols["Fecha"])))
    if len(fechas_comunes) == 0:
        raise ValueError("No hay fechas comunes entre los archivos. Verificá las columnas de fecha.")

    nov_f = nov_cols[nov_cols["Fecha"].isin(fechas_comunes)].sort_values("Fecha").reset_index(drop=True)
    dic_f = dic_cols[dic_cols["Fecha"].isin(fechas_comunes)].sort_values("Fecha").reset_index(drop=True)

    # Drop NaNs de Precio y volver a sincronizar por Fecha
    nov_f = nov_f.dropna(subset=["Precio"]).reset_index(drop=True)
    dic_f = dic_f.dropna(subset=["Precio"]).reset_index(drop=True)

    fechas_final = sorted(set(nov_f["Fecha"]).intersection(set(dic_f["Fecha"])))
    nov_final = nov_f[nov_f["Fecha"].isin(fechas_final)].sort_values("Fecha").reset_index(drop=True)
    dic_final = dic_f[dic_f["Fecha"].isin(fechas_final)].sort_values("Fecha").reset_index(drop=True)

    data = pd.DataFrame({
        "Fecha": nov_final["Fecha"],
        "NOV": nov_final["Precio"].values,
        "DIC": dic_final["Precio"].values,
    })
    data = data.dropna(subset=["NOV", "DIC"]).reset_index(drop=True)
    data["Spread"] = data["DIC"] - data["NOV"]

    print(f"Fechas comunes: {data['Fecha'].min().date()} -> {data['Fecha'].max().date()} | Observaciones: {len(data)}")
    return data

# --------------------------------------------------
# ======= REGRESIÓN SIMPLE (DIC ~ NOV) =============
# --------------------------------------------------
def regresion_simple(data):
    """Ajusta DIC ~ const + beta * NOV. Devuelve modelo y DataFrame con Predicha y Residuo."""
    df = data.copy()
    df_clean = df.dropna(subset=["NOV", "DIC"]).copy()
    if len(df_clean) < 5:
        print("Datos insuficientes para regresi\u00f3n (menos de 5 observaciones).")
        df["Predicha"] = np.nan
        df["Residuo"] = np.nan
        return None, df

    X = sm.add_constant(df_clean["NOV"])  # const + NOV
    y = df_clean["DIC"]
    modelo = sm.OLS(y, X).fit()

    # Asignar predicciones y residuos al DataFrame original alineando por indice
    df.loc[df_clean.index, "Predicha"] = modelo.predict(X)
    df.loc[df_clean.index, "Residuo"] = modelo.resid

    # residuo estandarizado (global)
    if not df["Residuo"].dropna().empty:
        df["Residuo_std"] = df["Residuo"] / df["Residuo"].std()
    else:
        df["Residuo_std"] = np.nan

    return modelo, df

# --------------------------------------------------
# ======= TESTS DE COINTEGRACION Y ADF =============
# --------------------------------------------------
def analizar_cointegracion(data, cfg=CONFIG):
    """Realiza coint(NOV,DIC) y ADF sobre Spread y sobre Residuo (si existe)."""
    resultados = {}
    df = data.dropna(subset=["NOV", "DIC"]) if "NOV" in data.columns and "DIC" in data.columns else data

    # Engle-Granger
    if len(df) < 10:
        resultados["coint_score"] = np.nan
        resultados["coint_pvalue"] = np.nan
        resultados["coint_rechaza"] = False
    else:
        try:
            score, pvalue, _ = coint(df["NOV"], df["DIC"])  # NOV first, DIC second
            resultados["coint_score"] = float(score)
            resultados["coint_pvalue"] = float(pvalue)
            resultados["coint_rechaza"] = pvalue < cfg["coint_pvalue_max"]
        except Exception as e:
            resultados["coint_score"] = np.nan
            resultados["coint_pvalue"] = np.nan
            resultados["coint_rechaza"] = False

    # ADF sobre Spread
    spread = data["Spread"].dropna()
    if len(spread) < 10:
        resultados["adf_statistic"] = np.nan
        resultados["adf_pvalue"] = np.nan
        resultados["adf_rechaza"] = False
    else:
        try:
            adf_res = adfuller(spread, autolag='AIC')
            resultados["adf_statistic"] = float(adf_res[0])
            resultados["adf_pvalue"] = float(adf_res[1])
            resultados["adf_rechaza"] = adf_res[1] < cfg["coint_pvalue_max"]
        except Exception:
            resultados["adf_statistic"] = np.nan
            resultados["adf_pvalue"] = np.nan
            resultados["adf_rechaza"] = False

    # ADF sobre Residuo (si disponible)
    if "Residuo" in data.columns and not data["Residuo"].dropna().empty:
        resid = data["Residuo"].dropna()
        if len(resid) >= 10:
            try:
                adf_r = adfuller(resid, autolag='AIC')
                resultados["adf_resid_statistic"] = float(adf_r[0])
                resultados["adf_resid_pvalue"] = float(adf_r[1])
                resultados["adf_resid_rechaza"] = adf_r[1] < cfg["coint_pvalue_max"]
            except Exception:
                resultados["adf_resid_statistic"] = np.nan
                resultados["adf_resid_pvalue"] = np.nan
                resultados["adf_resid_rechaza"] = False
        else:
            resultados["adf_resid_statistic"] = np.nan
            resultados["adf_resid_pvalue"] = np.nan
            resultados["adf_resid_rechaza"] = False

    return resultados

# --------------------------------------------------
# ======= Z-SCORES Y SEÑALES (ESTÁTICO + ROLLING) =
# --------------------------------------------------
def calcular_zscores_y_senales(data, cfg=CONFIG):
    df = data.copy()
    # Z-score estático del spread
    df["Zscore_Spread"] = (df["Spread"] - df["Spread"].mean()) / df["Spread"].std()

    # Z-score del residuo global
    if "Residuo" in df.columns and not df["Residuo"].dropna().empty:
        df["Zscore_Residuo"] = (df["Residuo"] - df["Residuo"].mean()) / df["Residuo"].std()
    else:
        df["Zscore_Residuo"] = np.nan

    # Z-score rolling (adaptativo)
    w = cfg.get("rolling_window", 60)
    if len(df) >= w:
        df["Residuo_roll_mean"] = df["Residuo"].rolling(window=w, min_periods=int(w/2)).mean()
        df["Residuo_roll_std"] = df["Residuo"].rolling(window=w, min_periods=int(w/2)).std()
        df["Zscore_Residuo_roll"] = (df["Residuo"] - df["Residuo_roll_mean"]) / df["Residuo_roll_std"]
    else:
        df["Residuo_roll_mean"] = np.nan
        df["Residuo_roll_std"] = np.nan
        df["Zscore_Residuo_roll"] = np.nan

    # Señales: priorizamos Zscore_Residuo_roll si existe, sino Zscore_Residuo, sino Zscore_Spread
    umbral = cfg.get("zscore_umbral", 1.5)
    df["Se\u00f1al"] = 0

    zcol = "Zscore_Residuo_roll" if "Zscore_Residuo_roll" in df.columns and not df["Zscore_Residuo_roll"].dropna().empty else (
        "Zscore_Residuo" if not df["Zscore_Residuo"].dropna().empty else "Zscore_Spread"
    )

    if zcol in df.columns:
        df.loc[df[zcol] < -umbral, "Se\u00f1al"] = 1   # Compra: spread bajo / residuo negativo
        df.loc[df[zcol] > umbral, "Se\u00f1al"] = -1  # Venta: spread alto / residuo positivo

    return df

# --------------------------------------------------
# ======= METRICAS SIMPLES DE TRADING ==============
# --------------------------------------------------
def calcular_metricas_trading(data, cfg=CONFIG):
    df = data.copy()
    umbral = cfg.get("zscore_umbral", 1.5)

    señales_compra = int((df["Se\u00f1al"] == 1).sum())
    señales_venta = int((df["Se\u00f1al"] == -1).sum())

    # Probabilidad simple de reversi\u00f3n al próximo paso: si en t|z|>umbral y |z_{t+1}|<|z_t|
    zcols = ["Zscore_Residuo_roll", "Zscore_Residuo", "Zscore_Spread"]
    zcol = next((c for c in zcols if c in df.columns and not df[c].dropna().empty), None)

    prob_reversion = np.nan
    if zcol is not None:
        z = df[zcol].values
        reversiones = 0
        total_extremos = 0
        for i in range(len(z)-1):
            if np.isnan(z[i]):
                continue
            if abs(z[i]) > umbral:
                total_extremos += 1
                if not np.isnan(z[i+1]) and abs(z[i+1]) < abs(z[i]):
                    reversiones += 1
        prob_reversion = (reversiones / total_extremos * 100) if total_extremos > 0 else np.nan

    metricas = {
        "señales_compra": señales_compra,
        "señales_venta": señales_venta,
        "prob_reversion_pct": prob_reversion,
        "zcol_usada": zcol
    }
    return metricas

# --------------------------------------------------
# ======= PANEL GRÁFICO COMPACTO ====================
# --------------------------------------------------
def panel_visual(data, resultados_coint=None, metricas=None, cfg=CONFIG):
    df = data.copy()
    fig, axs = plt.subplots(2, 3, figsize=(16, 9))
    fig.suptitle("Sistema de Trading de Reversi\u00f3n — NOV vs DIC", fontsize=14)

    # 1 - Spread
    axs[0,0].plot(df['Fecha'], df['Spread'], lw=1)
    axs[0,0].axhline(df['Spread'].mean(), linestyle='--')
    axs[0,0].set_title('Spread (DIC - NOV)')

    # 2 - Zscore elegido
    zcol = metricas.get('zcol_usada') if metricas else None
    if zcol and zcol in df.columns:
        axs[0,1].plot(df['Fecha'], df[zcol], lw=1)
        axs[0,1].axhline(0, color='black', lw=0.8)
        axs[0,1].axhline(cfg['zscore_umbral'], color='green', ls='--')
        axs[0,1].axhline(-cfg['zscore_umbral'], color='red', ls='--')
        axs[0,1].set_title(f'Z-score (usando: {zcol})')
    else:
        axs[0,1].text(0.5,0.5,'No hay Z-score calculado', ha='center')

    # 3 - residuos y señales
    if 'Residuo' in df.columns:
        axs[0,2].plot(df['Fecha'], df['Residuo'], lw=1)
        buy = df[df['Se\u00f1al']==1]
        sell = df[df['Se\u00f1al']==-1]
        axs[0,2].scatter(buy['Fecha'], buy['Residuo'], marker='^', color='green')
        axs[0,2].scatter(sell['Fecha'], sell['Residuo'], marker='v', color='red')
        axs[0,2].axhline(0, ls='--')
        axs[0,2].set_title('Residuos y Señales')

    # 4 - hist residuo
    if 'Residuo' in df.columns:
        axs[1,0].hist(df['Residuo'].dropna(), bins=30, density=False)
        axs[1,0].set_title('Histograma de residuos')

    # 5 - QQ plot
    if 'Residuo' in df.columns:
        stats.probplot(df['Residuo'].dropna(), dist='norm', plot=axs[1,1])
        axs[1,1].set_title('Q-Q plot')

    # 6 - texto resumen
    axs[1,2].axis('off')
    resumen = []
    if resultados_coint:
        resumen.append(f"coint p-value: {resultados_coint.get('coint_pvalue', np.nan):.4f}")
        resumen.append(f"ADF spread p-value: {resultados_coint.get('adf_pvalue', np.nan):.4f}")
        resumen.append(f"ADF resid p-value: {resultados_coint.get('adf_resid_pvalue', np.nan):.4f}")
    if metricas:
        resumen.append(f"Señales compra: {metricas.get('señales_compra',0)}")
        resumen.append(f"Señales venta: {metricas.get('señales_venta',0)}")
        resumen.append(f"Prob rev (%): {metricas.get('prob_reversion_pct',np.nan):.2f}")
    axs[1,2].text(0,0.9, '\n'.join(resumen), fontsize=10)

    plt.tight_layout(rect=[0,0,1,0.96])
    plt.show()

# --------------------------------------------------
# ======= EXPORTAR RESULTADOS A EXCEL ==============
# --------------------------------------------------
def exportar_resultados(data, resultados_coint, metricas, modelo, cfg=CONFIG):
    writer = pd.ExcelWriter(cfg.get('output_excel', 'resultado_reversion.xlsx'), engine='xlsxwriter')
    data.to_excel(writer, sheet_name='data', index=False)
    pd.DataFrame([resultados_coint]).to_excel(writer, sheet_name='cointegracion', index=False)
    pd.DataFrame([metricas]).to_excel(writer, sheet_name='metricas', index=False)
    if modelo is not None:
        # parametros del modelo
        params = modelo.params
        try:
            summary_df = pd.read_html(modelo.summary().tables[1].as_html(), header=0, index_col=0)[0]
            summary_df.to_excel(writer, sheet_name='regression_summary')
        except Exception:
            pd.DataFrame(params).to_excel(writer, sheet_name='regression_params')
    writer.save()
    print(f"Resultados exportados a: {cfg.get('output_excel')}")

# --------------------------------------------------
# ======= MAIN =====================================
# --------------------------------------------------
def run_all(cfg=CONFIG):
    data = cargar_series(cfg)
    modelo, data = regresion_simple(data)
    resultados_coint = analizar_cointegracion(data, cfg)
    data = calcular_zscores_y_senales(data, cfg)
    metricas = calcular_metricas_trading(data, cfg)
    panel_visual(data, resultados_coint, metricas, cfg)
    exportar_resultados(data, resultados_coint, metricas, modelo, cfg)

    # resumen impreso
    print('\n=== Resumen rapido ===')
    print(f"Cointegracion (p-value): {resultados_coint.get('coint_pvalue', np.nan)}")
    print(f"ADF spread (p-value): {resultados_coint.get('adf_pvalue', np.nan)}")
    print(f"ADF resid (p-value): {resultados_coint.get('adf_resid_pvalue', np.nan)}")
    if modelo is not None:
        print(f"Regresion R2: {modelo.rsquared:.4f} | beta: {modelo.params.get('NOV', np.nan):.4f}")

    return data, modelo, resultados_coint, metricas

# --------------------------------------------------
if __name__ == '__main__':
    run_all(CONFIG)